#!/bin/sh
#
# Start the Palo Alto Networks Global Protect VPN software.
#
# This implementation uses `launchctl` to load the code.
##
set -uf

launchctl load -w /Library/LaunchAgents/com.paloaltonetworks.gp.pangps.plist
launchctl load -w /Library/LaunchAgents/com.paloaltonetworks.gp.pangpa.plist
